[programs.localnet]
non_custodial_escrow = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/rok_hribar/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
